"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect,useRef } from "react";
import { titleInlineText,type Title } from "@/lib/content";
import type { CategoryTile,TitleCollections } from "@/lib/payload-content";
import { getPrototypeCategories,titleCategories,type PrototypeCategory } from "./blog-data";
type HomeProps={categoryTiles:CategoryTile[];collections:TitleCollections;titles:Title[]};type CategoryProps={category:PrototypeCategory;titles:Title[]};type ArticleProps={related:Title[];title:Title};
// Category data remains part of the shared home contract; this direction uses program-derived categories in its navigation.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function StyleElevenHome({categoryTiles,collections,titles}:HomeProps){const available=titles.filter(x=>!x.isDiscontinued);const lead=collections.heroes[0]??available.find(x=>x.featured)??available[0];const supporting=unique([...available.filter(x=>x.featured),...collections.recommended,...available]).find(x=>x.slug!==lead?.slug);const recent=unique([...available.filter(x=>x.isNew),...available]).filter(x=>x.slug!==lead?.slug).slice(0,5);const recommended=unique([...collections.recommended,...available]).slice(0,5);return <ElevenMotion><div className="s11-shell" id="top"><ElevenHeader categories={getPrototypeCategories(titles)}/><main>{lead?<EditorialOpening lead={lead} supporting={supporting}/>:null}<RecentFeed titles={recent}/><Statement/><Discovery title={recommended[0]??lead}/><VisualGallery titles={recommended}/><Recommended titles={recommended.slice(1)}/><FinalInvitation/></main><ElevenFooter categories={getPrototypeCategories(titles)}/></div></ElevenMotion>}
export function StyleElevenCategory({category,titles}:CategoryProps){return <ElevenMotion><div className="s11-shell s11-inner"><ElevenHeader categories={getPrototypeCategories(titles)}/><main><header className="s11-index-head" data-s11-reveal><p>Thai PBS / Editorial collection</p><h1>{category.label}</h1><span>{titles.length} thoughtful selections</span></header><section className="s11-index-feed">{titles.map((title,index)=><RecentRow index={index} key={title.slug} title={title}/>)}</section></main><ElevenFooter categories={getPrototypeCategories(titles)}/></div></ElevenMotion>}
export function StyleElevenArticle({related,title}:ArticleProps){const category=titleCategories(title)[0];return <ElevenMotion><div className="s11-shell s11-inner"><ElevenHeader categories={getPrototypeCategories([title,...related])}/><main><article className="s11-article"><EditorialImage className="s11-article__image" priority title={title}/><header data-s11-reveal><p>{category.label}</p><h1>{titleInlineText(title)}</h1><span>{[title.year,title.duration,title.type].filter(Boolean).join(" · ")}</span></header><div className="s11-article__body"><p>{title.description}</p><dl><div><dt>Category</dt><dd>{category.label}</dd></div><div><dt>Format</dt><dd>{title.type}</dd></div><div><dt>Duration</dt><dd>{title.duration||"—"}</dd></div></dl></div></article>{related.length?<section className="s11-related"><SectionTitle eyebrow="Continue reading" title="More stories"/><div>{related.slice(0,3).map((item,index)=><QuietCard index={index} key={item.slug} title={item}/>)}</div></section>:null}</main><ElevenFooter categories={getPrototypeCategories([title,...related])}/></div></ElevenMotion>}
function ElevenMotion({children}:{children:React.ReactNode}){const root=useRef<HTMLDivElement>(null);useEffect(()=>{const el=root.current;if(!el)return;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const header=el.querySelector<HTMLElement>(".s11-header");let previous=scrollY;const onScroll=()=>{const next=scrollY;header?.classList.toggle("is-hidden",next>previous&&next>160);previous=next};addEventListener("scroll",onScroll,{passive:true});if(reduced)return()=>removeEventListener("scroll",onScroll);const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.12});el.querySelectorAll<HTMLElement>("[data-s11-reveal]").forEach(x=>observer.observe(x));return()=>{removeEventListener("scroll",onScroll);observer.disconnect()}},[]);return <div className="style-eleven" ref={root}>{children}</div>}
function ElevenHeader({categories}:{categories:PrototypeCategory[]}){return <header className="s11-header"><Link className="s11-brand" href="/prototype/style-11"><b>Thai PBS</b><span>Stories for a thoughtful day</span></Link><nav><a href="#recent">Recent</a><a href="#discover">Discover</a><a href="#recommended">Recommended</a></nav><details><summary>Menu ＋</summary><div>{categories.slice(0,6).map(x=><Link href={`/prototype/style-11/category/${x.slug}`} key={x.slug}>{x.label}</Link>)}</div></details></header>}
function EditorialOpening({lead,supporting}:{lead:Title;supporting?:Title}){return <section className="s11-opening"><Link className="s11-opening__main" href={`/prototype/style-11/article/${lead.slug}`}><EditorialImage priority title={lead}/></Link><div className="s11-opening__thought" data-s11-reveal><p>Stories in focus</p>{supporting?<EditorialImage portrait title={supporting}/>:null}<span>{titleCategories(lead)[0]?.label}</span><h1>{titleInlineText(lead)}</h1><small>{lead.description}</small><Link href={`/prototype/style-11/article/${lead.slug}`}>Explore this story →</Link></div></section>}
function RecentFeed({titles}:{titles:Title[]}){if(!titles.length)return null;return <section className="s11-recent" id="recent"><SectionTitle eyebrow="Fresh from Thai PBS" title="Recent programs"/>{titles.map((title,index)=><RecentRow index={index} key={title.slug} title={title}/>)}</section>}
function RecentRow({index,title}:{index:number;title:Title}){return <Link className={`s11-row s11-row--${index%2}`} href={`/prototype/style-11/article/${title.slug}`} data-s11-reveal><EditorialImage portrait={index%3===1} title={title}/><div><p>{titleCategories(title)[0]?.label} · {title.duration||title.type}</p><h3>{titleInlineText(title)}</h3><span>{title.description}</span><b>Read more →</b></div></Link>}
function Statement(){return <section className="s11-statement" data-s11-reveal><blockquote>“เรื่องราวรอบตัวเรา อาจเปลี่ยนวิธีที่เรามองโลกได้เสมอ”</blockquote><p>Thai PBS · Stories that matter</p></section>}
function Discovery({title}:{title?:Title}){if(!title)return null;return <section className="s11-discovery" id="discover" data-s11-reveal><EditorialImage portrait title={title}/><div><p>Discover Thai PBS</p><h2>More than television.<br/>A place for perspective.</h2><span>{title.description}</span><Link href={`/prototype/style-11/article/${title.slug}`}>Begin exploring →</Link></div></section>}
function VisualGallery({titles}:{titles:Title[]}){if(!titles.length)return null;return <section className="s11-gallery"><SectionTitle eyebrow="A visual pause" title="Stories that stay with us"/><div>{titles.slice(0,5).map((title,index)=><Link href={`/prototype/style-11/article/${title.slug}`} key={title.slug}><EditorialImage portrait={index===1||index===4} title={title}/><span>{titleInlineText(title)}</span></Link>)}</div></section>}
function Recommended({titles}:{titles:Title[]}){if(!titles.length)return null;return <section className="s11-recommended" id="recommended"><SectionTitle eyebrow="Selected for you" title="Recommended"/><div>{titles.map((title,index)=><QuietCard index={index} key={title.slug} title={title}/>)}</div></section>}
function QuietCard({index,title}:{index:number;title:Title}){return <Link className={`s11-card s11-card--${index%4}`} href={`/prototype/style-11/article/${title.slug}`} data-s11-reveal><EditorialImage portrait={index%4===1} title={title}/><p>{titleCategories(title)[0]?.label}</p><h3>{titleInlineText(title)}</h3><span>{title.description}</span></Link>}
function FinalInvitation(){return <section className="s11-invitation" data-s11-reveal><p>Keep the conversation going</p><h2>Find another story<br/>for today.</h2><a href="#recent">Browse recent programs →</a></section>}
function SectionTitle({eyebrow,title}:{eyebrow:string;title:string}){return <header className="s11-section-title" data-s11-reveal><p>{eyebrow}</p><h2>{title}</h2></header>}
function EditorialImage({className="",portrait=false,priority=false,title}:{className?:string;portrait?:boolean;priority?:boolean;title:Title}){const image=portrait?(title.posterImage||title.heroImage):(title.heroImage||title.posterImage);return <div className={`s11-image ${portrait?"s11-image--portrait":""} ${className}`}>{image?<Image alt="" fill priority={priority} sizes={portrait?"(max-width:700px) 85vw,35vw":"(max-width:700px) 100vw,65vw"} src={image}/>:<span data-tone={Math.abs(hash(title.slug))%4}/>}</div>}
function ElevenFooter({categories}:{categories:PrototypeCategory[]}){return <footer className="s11-footer"><Link className="s11-brand" href="/prototype/style-11"><b>Thai PBS</b><span>Stories for a thoughtful day</span></Link><nav>{categories.slice(0,6).map(x=><Link href={`/prototype/style-11/category/${x.slug}`} key={x.slug}>{x.label}</Link>)}</nav><a href="#top">Back to top ↑</a></footer>}
function unique(items:Title[]){return [...new Map(items.map(x=>[x.slug,x])).values()]}function hash(value:string){return [...value].reduce((t,c)=>((t<<5)-t)+c.charCodeAt(0),0)}
