/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    roleProfiles: RoleProfile;
    userGroups: UserGroup;
    media: Media;
    videos: Video;
    landing: Landing;
    trends: Trend;
    content: Content;
    header: Header;
    footer: Footer;
    languages: Language;
    awards: Award;
    categories: Category;
    genres: Genre;
    subGenres: SubGenre;
    heroImages: HeroImage;
    programs: Program;
    vipaPrograms: VipaProgram;
    seasons: Season;
    episodes: Episode;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    roleProfiles: RoleProfilesSelect<false> | RoleProfilesSelect<true>;
    userGroups: UserGroupsSelect<false> | UserGroupsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    landing: LandingSelect<false> | LandingSelect<true>;
    trends: TrendsSelect<false> | TrendsSelect<true>;
    content: ContentSelect<false> | ContentSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    languages: LanguagesSelect<false> | LanguagesSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    subGenres: SubGenresSelect<false> | SubGenresSelect<true>;
    heroImages: HeroImagesSelect<false> | HeroImagesSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    vipaPrograms: VipaProgramsSelect<false> | VipaProgramsSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    episodes: EpisodesSelect<false> | EpisodesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Only Super Admin is built in. All other access comes from CMS roles or groups.
   */
  role: 'super-admin' | 'user';
  /**
   * CMS-created permission roles assigned to this user.
   */
  roles?: (number | RoleProfile)[] | null;
  /**
   * Permission groups this user belongs to.
   */
  groups?: (number | UserGroup)[] | null;
  /**
   * Programs this user owns. When set, program access is scoped to these rows.
   */
  ownedPrograms?: (number | Program)[] | null;
  /**
   * VIPA programs this user owns. When set, VIPA program access is scoped to these rows.
   */
  ownedVipaPrograms?: (number | VipaProgram)[] | null;
  /**
   * Optional extra admin pages this user can view.
   */
  allowedAdminPages?:
    | (
        | 'dashboard'
        | 'season-sales'
        | 'programs-manager'
        | 'add-program-season-ep'
        | 'programs-manager-edit'
        | 'programs-detail-upload'
        | 'trends-upload'
        | 'large-video-upload'
      )[]
    | null;
  /**
   * Optional direct collection permissions for this user.
   */
  collectionPermissions?:
    | {
        collection:
          | 'users'
          | 'roleProfiles'
          | 'userGroups'
          | 'media'
          | 'videos'
          | 'landing'
          | 'trends'
          | 'content'
          | 'header'
          | 'footer'
          | 'languages'
          | 'awards'
          | 'programs'
          | 'vipaPrograms'
          | 'seasons'
          | 'episodes';
        /**
         * Choose one or more actions for this collection.
         */
        operations: ('read' | 'create' | 'update' | 'delete')[];
        id?: string | null;
      }[]
    | null;
  /**
   * Optional direct field permissions for this user.
   */
  fieldPermissions?:
    | {
        collection:
          | 'users'
          | 'roleProfiles'
          | 'userGroups'
          | 'media'
          | 'videos'
          | 'landing'
          | 'trends'
          | 'content'
          | 'header'
          | 'footer'
          | 'languages'
          | 'awards'
          | 'programs'
          | 'vipaPrograms'
          | 'seasons'
          | 'episodes';
        /**
         * Allow create/update of every field in this collection.
         */
        allFields?: boolean | null;
        /**
         * Legacy field list. Prefer the collection-specific picker below.
         */
        fields?: string[] | null;
        /**
         * Editable fields from users.
         */
        fields_users?:
          | (
              | 'email'
              | 'role'
              | 'roles'
              | 'groups'
              | 'ownedPrograms'
              | 'ownedVipaPrograms'
              | 'allowedAdminPages'
              | 'collectionPermissions'
              | 'fieldPermissions'
            )[]
          | null;
        /**
         * Editable fields from roleProfiles.
         */
        fields_roleProfiles?:
          ('name' | 'users' | 'allowedAdminPages' | 'collectionPermissions' | 'fieldPermissions')[] | null;
        /**
         * Editable fields from userGroups.
         */
        fields_userGroups?:
          | (
              | 'name'
              | 'users'
              | 'ownedPrograms'
              | 'ownedVipaPrograms'
              | 'allowedAdminPages'
              | 'collectionPermissions'
              | 'fieldPermissions'
            )[]
          | null;
        /**
         * Editable fields from media.
         */
        fields_media?: ('title' | 'alt')[] | null;
        /**
         * Editable fields from videos.
         */
        fields_videos?: ('title' | 'alt')[] | null;
        /**
         * Editable fields from landing.
         */
        fields_landing?: ('title' | 'heroImage')[] | null;
        /**
         * Editable fields from trends.
         */
        fields_trends?: ('type' | 'title' | 'link' | 'image' | 'boxHeight')[] | null;
        /**
         * Editable fields from content.
         */
        fields_content?: ('slug' | 'titleTh' | 'titleEn' | 'topicSections' | 'contentTh' | 'contentEn')[] | null;
        /**
         * Editable fields from header.
         */
        fields_header?: ('titleTh' | 'titleEn' | 'items')[] | null;
        /**
         * Editable fields from footer.
         */
        fields_footer?: ('titleTh' | 'titleEn' | 'items')[] | null;
        /**
         * Editable fields from languages.
         */
        fields_languages?: ('code' | 'label')[] | null;
        /**
         * Editable fields from awards.
         */
        fields_awards?: 'name'[] | null;
        /**
         * Editable fields from programs.
         */
        fields_programs?:
          | (
              | 'programId'
              | 'slug'
              | 'titleTh'
              | 'titleEn'
              | 'programContentType'
              | 'comingSoon'
              | 'comingSoonDate'
              | 'synopsisTh'
              | 'synopsisEn'
              | 'companyProduce'
              | 'producer'
              | 'artist'
              | 'writer'
              | 'targetGroup'
              | 'programType'
              | 'genre'
              | 'subGenre'
              | 'tags'
              | 'comment'
              | 'image'
              | 'coverImage'
              | 'trailer'
              | 'video'
              | 'TrailerAirflowProxyPath'
              | 'TrailerThumbnailAirflowProxyPath'
              | 'videoAirflowProxyPath'
              | 'videoThumbnailAirflowProxyPath'
              | 'videoLink'
              | 'trailerLink'
              | 'is_IP'
              | 'is_Feature'
              | 'is_NEW'
              | 'is_Schedule'
              | 'isNewHits'
              | 'is_Award'
              | 'is_special_programs'
              | 'is_old_series'
              | 'is_continue'
              | 'is_global_programs'
              | 'is_global_international'
              | 'is_global_thai_dub'
              | 'is_normal_programs'
              | 'is_Detail'
              | 'hasSoundtrack'
              | 'hasAd'
              | 'hasCc'
              | 'hasSl'
              | 'hasBigSign'
              | 'isUncut'
              | 'firstRun'
              | 'rerunDates'
              | 'space'
              | 'format'
              | 'duration'
              | 'onThaipbs'
              | 'onAltv'
              | 'onVipa'
              | 'onFacebook'
              | 'onX'
              | 'onYoutube'
              | 'onTiktok'
              | 'views'
              | 'productionCountry'
              | 'productionYear'
              | 'rightsTerritoriesAvailable'
              | 'audioChannel1'
              | 'audioChannel2'
              | 'closeCaption1'
              | 'closeCaption2'
              | 'closeCaption3'
              | 'subtitle1'
              | 'file_type'
              | 'version'
              | 'file_ext'
              | 'is_infosheet_write'
              | 'asset_create'
              | 'asset_update'
              | 'seasons'
            )[]
          | null;
        /**
         * Editable fields from vipaPrograms.
         */
        fields_vipaPrograms?:
          | (
              | 'titleTh'
              | 'titleEn'
              | 'isNEW'
              | 'isSchedule'
              | 'isNewHits'
              | 'is_special_programs'
              | 'is_old_series'
              | 'isFeature'
              | 'is_IP'
              | 'isThaiProgram'
              | 'isInterProgram'
              | 'image'
              | 'coverImage'
              | 'vipaLink'
              | 'genre'
              | 'tags'
              | 'firstRun'
              | 'rerunDates'
              | 'duration'
              | 'hasSoundtrack'
              | 'hasAd'
              | 'hasCc'
              | 'hasSl'
              | 'hasBigSign'
              | 'isUncut'
              | 'epCount'
              | 'views'
            )[]
          | null;
        /**
         * Editable fields from seasons.
         */
        fields_seasons?:
          | (
              | 'program'
              | 'season'
              | 'seasonName'
              | 'seasonNameEn'
              | 'is_Award'
              | 'awards'
              | 'hasCc'
              | 'languages'
              | 'hasSoundtrack'
              | 'languagesSoundtrack'
              | 'comingSoon'
              | 'comingSoonDate'
              | 'synopsisTh'
              | 'synopsisEn'
              | 'coverImage'
              | 'trailer'
              | 'video'
              | 'TrailerAirflowProxyPath'
              | 'TrailerThumbnailAirflowProxyPath'
              | 'videoAirflowProxyPath'
              | 'videoThumbnailAirflowProxyPath'
              | 'videoLink'
              | 'trailerLink'
              | 'sellPricing'
              | 'episodes'
            )[]
          | null;
        /**
         * Editable fields from episodes.
         */
        fields_episodes?:
          | (
              | 'season'
              | 'ep'
              | 'epNameTh'
              | 'epNameEn'
              | 'comingSoon'
              | 'comingSoonDate'
              | 'firstRun'
              | 'rerunDates'
              | 'synopsisEpTh'
              | 'synopsisEpEn'
              | 'coverImage'
              | 'trailer'
              | 'video'
              | 'TrailerAirflowProxyPath'
              | 'TrailerThumbnailAirflowProxyPath'
              | 'videoAirflowProxyPath'
              | 'videoThumbnailAirflowProxyPath'
              | 'videoLink'
              | 'trailerLink'
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy document assignments kept for legacy data only. Collection and field permissions control access.
   */
  allowedDocuments?:
    | (
        | {
            relationTo: 'users';
            value: number | User;
          }
        | {
            relationTo: 'roleProfiles';
            value: number | RoleProfile;
          }
        | {
            relationTo: 'userGroups';
            value: number | UserGroup;
          }
        | {
            relationTo: 'media';
            value: number | Media;
          }
        | {
            relationTo: 'videos';
            value: number | Video;
          }
        | {
            relationTo: 'landing';
            value: number | Landing;
          }
        | {
            relationTo: 'trends';
            value: number | Trend;
          }
        | {
            relationTo: 'content';
            value: number | Content;
          }
        | {
            relationTo: 'header';
            value: number | Header;
          }
        | {
            relationTo: 'footer';
            value: number | Footer;
          }
        | {
            relationTo: 'languages';
            value: number | Language;
          }
        | {
            relationTo: 'awards';
            value: number | Award;
          }
        | {
            relationTo: 'programs';
            value: number | Program;
          }
        | {
            relationTo: 'vipaPrograms';
            value: number | VipaProgram;
          }
        | {
            relationTo: 'seasons';
            value: number | Season;
          }
        | {
            relationTo: 'episodes';
            value: number | Episode;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'users';
}
/**
 * CMS-created permission roles. Super Admin is the only built-in role.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roleProfiles".
 */
export interface RoleProfile {
  id: number;
  /**
   * Role name, for example Producer or Editor.
   */
  name: string;
  /**
   * Users assigned to this CMS role.
   */
  users?: (number | User)[] | null;
  /**
   * Admin pages this role can view.
   */
  allowedAdminPages?:
    | (
        | 'dashboard'
        | 'season-sales'
        | 'programs-manager'
        | 'add-program-season-ep'
        | 'programs-manager-edit'
        | 'programs-detail-upload'
        | 'trends-upload'
        | 'large-video-upload'
      )[]
    | null;
  /**
   * Collections this role can read, create, update, or delete.
   */
  collectionPermissions?:
    | {
        collection:
          | 'users'
          | 'roleProfiles'
          | 'userGroups'
          | 'media'
          | 'videos'
          | 'landing'
          | 'trends'
          | 'content'
          | 'header'
          | 'footer'
          | 'languages'
          | 'awards'
          | 'programs'
          | 'vipaPrograms'
          | 'seasons'
          | 'episodes';
        /**
         * Choose one or more actions for this collection.
         */
        operations: ('read' | 'create' | 'update' | 'delete')[];
        id?: string | null;
      }[]
    | null;
  /**
   * Fields this role can create or update. Use All Fields to allow every field.
   */
  fieldPermissions?:
    | {
        collection:
          | 'users'
          | 'roleProfiles'
          | 'userGroups'
          | 'media'
          | 'videos'
          | 'landing'
          | 'trends'
          | 'content'
          | 'header'
          | 'footer'
          | 'languages'
          | 'awards'
          | 'programs'
          | 'vipaPrograms'
          | 'seasons'
          | 'episodes';
        /**
         * Allow create/update of every field in this collection.
         */
        allFields?: boolean | null;
        /**
         * Legacy field list. Prefer the collection-specific picker below.
         */
        fields?: string[] | null;
        /**
         * Editable fields from users.
         */
        fields_users?:
          | (
              | 'email'
              | 'role'
              | 'roles'
              | 'groups'
              | 'ownedPrograms'
              | 'ownedVipaPrograms'
              | 'allowedAdminPages'
              | 'collectionPermissions'
              | 'fieldPermissions'
            )[]
          | null;
        /**
         * Editable fields from roleProfiles.
         */
        fields_roleProfiles?:
          ('name' | 'users' | 'allowedAdminPages' | 'collectionPermissions' | 'fieldPermissions')[] | null;
        /**
         * Editable fields from userGroups.
         */
        fields_userGroups?:
          | (
              | 'name'
              | 'users'
              | 'ownedPrograms'
              | 'ownedVipaPrograms'
              | 'allowedAdminPages'
              | 'collectionPermissions'
              | 'fieldPermissions'
            )[]
          | null;
        /**
         * Editable fields from media.
         */
        fields_media?: ('title' | 'alt')[] | null;
        /**
         * Editable fields from videos.
         */
        fields_videos?: ('title' | 'alt')[] | null;
        /**
         * Editable fields from landing.
         */
        fields_landing?: ('title' | 'heroImage')[] | null;
        /**
         * Editable fields from trends.
         */
        fields_trends?: ('type' | 'title' | 'link' | 'image' | 'boxHeight')[] | null;
        /**
         * Editable fields from content.
         */
        fields_content?: ('slug' | 'titleTh' | 'titleEn' | 'topicSections' | 'contentTh' | 'contentEn')[] | null;
        /**
         * Editable fields from header.
         */
        fields_header?: ('titleTh' | 'titleEn' | 'items')[] | null;
        /**
         * Editable fields from footer.
         */
        fields_footer?: ('titleTh' | 'titleEn' | 'items')[] | null;
        /**
         * Editable fields from languages.
         */
        fields_languages?: ('code' | 'label')[] | null;
        /**
         * Editable fields from awards.
         */
        fields_awards?: 'name'[] | null;
        /**
         * Editable fields from programs.
         */
        fields_programs?:
          | (
              | 'programId'
              | 'slug'
              | 'titleTh'
              | 'titleEn'
              | 'programContentType'
              | 'comingSoon'
              | 'comingSoonDate'
              | 'synopsisTh'
              | 'synopsisEn'
              | 'companyProduce'
              | 'producer'
              | 'artist'
              | 'writer'
              | 'targetGroup'
              | 'programType'
              | 'genre'
              | 'subGenre'
              | 'tags'
              | 'comment'
              | 'image'
              | 'coverImage'
              | 'trailer'
              | 'video'
              | 'TrailerAirflowProxyPath'
              | 'TrailerThumbnailAirflowProxyPath'
              | 'videoAirflowProxyPath'
              | 'videoThumbnailAirflowProxyPath'
              | 'videoLink'
              | 'trailerLink'
              | 'is_IP'
              | 'is_Feature'
              | 'is_NEW'
              | 'is_Schedule'
              | 'isNewHits'
              | 'is_Award'
              | 'is_special_programs'
              | 'is_old_series'
              | 'is_continue'
              | 'is_global_programs'
              | 'is_global_international'
              | 'is_global_thai_dub'
              | 'is_normal_programs'
              | 'is_Detail'
              | 'hasSoundtrack'
              | 'hasAd'
              | 'hasCc'
              | 'hasSl'
              | 'hasBigSign'
              | 'isUncut'
              | 'firstRun'
              | 'rerunDates'
              | 'space'
              | 'format'
              | 'duration'
              | 'onThaipbs'
              | 'onAltv'
              | 'onVipa'
              | 'onFacebook'
              | 'onX'
              | 'onYoutube'
              | 'onTiktok'
              | 'views'
              | 'productionCountry'
              | 'productionYear'
              | 'rightsTerritoriesAvailable'
              | 'audioChannel1'
              | 'audioChannel2'
              | 'closeCaption1'
              | 'closeCaption2'
              | 'closeCaption3'
              | 'subtitle1'
              | 'file_type'
              | 'version'
              | 'file_ext'
              | 'is_infosheet_write'
              | 'asset_create'
              | 'asset_update'
              | 'seasons'
            )[]
          | null;
        /**
         * Editable fields from vipaPrograms.
         */
        fields_vipaPrograms?:
          | (
              | 'titleTh'
              | 'titleEn'
              | 'isNEW'
              | 'isSchedule'
              | 'isNewHits'
              | 'is_special_programs'
              | 'is_old_series'
              | 'isFeature'
              | 'is_IP'
              | 'isThaiProgram'
              | 'isInterProgram'
              | 'image'
              | 'coverImage'
              | 'vipaLink'
              | 'genre'
              | 'tags'
              | 'firstRun'
              | 'rerunDates'
              | 'duration'
              | 'hasSoundtrack'
              | 'hasAd'
              | 'hasCc'
              | 'hasSl'
              | 'hasBigSign'
              | 'isUncut'
              | 'epCount'
              | 'views'
            )[]
          | null;
        /**
         * Editable fields from seasons.
         */
        fields_seasons?:
          | (
              | 'program'
              | 'season'
              | 'seasonName'
              | 'seasonNameEn'
              | 'is_Award'
              | 'awards'
              | 'hasCc'
              | 'languages'
              | 'hasSoundtrack'
              | 'languagesSoundtrack'
              | 'comingSoon'
              | 'comingSoonDate'
              | 'synopsisTh'
              | 'synopsisEn'
              | 'coverImage'
              | 'trailer'
              | 'video'
              | 'TrailerAirflowProxyPath'
              | 'TrailerThumbnailAirflowProxyPath'
              | 'videoAirflowProxyPath'
              | 'videoThumbnailAirflowProxyPath'
              | 'videoLink'
              | 'trailerLink'
              | 'sellPricing'
              | 'episodes'
            )[]
          | null;
        /**
         * Editable fields from episodes.
         */
        fields_episodes?:
          | (
              | 'season'
              | 'ep'
              | 'epNameTh'
              | 'epNameEn'
              | 'comingSoon'
              | 'comingSoonDate'
              | 'firstRun'
              | 'rerunDates'
              | 'synopsisEpTh'
              | 'synopsisEpEn'
              | 'coverImage'
              | 'trailer'
              | 'video'
              | 'TrailerAirflowProxyPath'
              | 'TrailerThumbnailAirflowProxyPath'
              | 'videoAirflowProxyPath'
              | 'videoThumbnailAirflowProxyPath'
              | 'videoLink'
              | 'trailerLink'
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy document assignments kept for legacy data only. Collection and field permissions control access.
   */
  allowedDocuments?:
    | (
        | {
            relationTo: 'users';
            value: number | User;
          }
        | {
            relationTo: 'roleProfiles';
            value: number | RoleProfile;
          }
        | {
            relationTo: 'userGroups';
            value: number | UserGroup;
          }
        | {
            relationTo: 'media';
            value: number | Media;
          }
        | {
            relationTo: 'videos';
            value: number | Video;
          }
        | {
            relationTo: 'landing';
            value: number | Landing;
          }
        | {
            relationTo: 'trends';
            value: number | Trend;
          }
        | {
            relationTo: 'content';
            value: number | Content;
          }
        | {
            relationTo: 'header';
            value: number | Header;
          }
        | {
            relationTo: 'footer';
            value: number | Footer;
          }
        | {
            relationTo: 'languages';
            value: number | Language;
          }
        | {
            relationTo: 'awards';
            value: number | Award;
          }
        | {
            relationTo: 'programs';
            value: number | Program;
          }
        | {
            relationTo: 'vipaPrograms';
            value: number | VipaProgram;
          }
        | {
            relationTo: 'seasons';
            value: number | Season;
          }
        | {
            relationTo: 'episodes';
            value: number | Episode;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Permission groups for clients, departments, or partners.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userGroups".
 */
export interface UserGroup {
  id: number;
  /**
   * Group name, for example Toyota.
   */
  name: string;
  /**
   * Users who belong to this group.
   */
  users?: (number | User)[] | null;
  /**
   * Programs owned by members of this group.
   */
  ownedPrograms?: (number | Program)[] | null;
  /**
   * VIPA programs owned by members of this group.
   */
  ownedVipaPrograms?: (number | VipaProgram)[] | null;
  /**
   * Optional extra admin pages members can view.
   */
  allowedAdminPages?:
    | (
        | 'dashboard'
        | 'season-sales'
        | 'programs-manager'
        | 'add-program-season-ep'
        | 'programs-manager-edit'
        | 'programs-detail-upload'
        | 'trends-upload'
        | 'large-video-upload'
      )[]
    | null;
  /**
   * Collections group members can read, create, update, or delete.
   */
  collectionPermissions?:
    | {
        collection:
          | 'users'
          | 'roleProfiles'
          | 'userGroups'
          | 'media'
          | 'videos'
          | 'landing'
          | 'trends'
          | 'content'
          | 'header'
          | 'footer'
          | 'languages'
          | 'awards'
          | 'programs'
          | 'vipaPrograms'
          | 'seasons'
          | 'episodes';
        /**
         * Choose one or more actions for this collection.
         */
        operations: ('read' | 'create' | 'update' | 'delete')[];
        id?: string | null;
      }[]
    | null;
  /**
   * Fields group members can create or update. Use All Fields to allow every field.
   */
  fieldPermissions?:
    | {
        collection:
          | 'users'
          | 'roleProfiles'
          | 'userGroups'
          | 'media'
          | 'videos'
          | 'landing'
          | 'trends'
          | 'content'
          | 'header'
          | 'footer'
          | 'languages'
          | 'awards'
          | 'programs'
          | 'vipaPrograms'
          | 'seasons'
          | 'episodes';
        /**
         * Allow create/update of every field in this collection.
         */
        allFields?: boolean | null;
        /**
         * Legacy field list. Prefer the collection-specific picker below.
         */
        fields?: string[] | null;
        /**
         * Editable fields from users.
         */
        fields_users?:
          | (
              | 'email'
              | 'role'
              | 'roles'
              | 'groups'
              | 'ownedPrograms'
              | 'ownedVipaPrograms'
              | 'allowedAdminPages'
              | 'collectionPermissions'
              | 'fieldPermissions'
            )[]
          | null;
        /**
         * Editable fields from roleProfiles.
         */
        fields_roleProfiles?:
          ('name' | 'users' | 'allowedAdminPages' | 'collectionPermissions' | 'fieldPermissions')[] | null;
        /**
         * Editable fields from userGroups.
         */
        fields_userGroups?:
          | (
              | 'name'
              | 'users'
              | 'ownedPrograms'
              | 'ownedVipaPrograms'
              | 'allowedAdminPages'
              | 'collectionPermissions'
              | 'fieldPermissions'
            )[]
          | null;
        /**
         * Editable fields from media.
         */
        fields_media?: ('title' | 'alt')[] | null;
        /**
         * Editable fields from videos.
         */
        fields_videos?: ('title' | 'alt')[] | null;
        /**
         * Editable fields from landing.
         */
        fields_landing?: ('title' | 'heroImage')[] | null;
        /**
         * Editable fields from trends.
         */
        fields_trends?: ('type' | 'title' | 'link' | 'image' | 'boxHeight')[] | null;
        /**
         * Editable fields from content.
         */
        fields_content?: ('slug' | 'titleTh' | 'titleEn' | 'topicSections' | 'contentTh' | 'contentEn')[] | null;
        /**
         * Editable fields from header.
         */
        fields_header?: ('titleTh' | 'titleEn' | 'items')[] | null;
        /**
         * Editable fields from footer.
         */
        fields_footer?: ('titleTh' | 'titleEn' | 'items')[] | null;
        /**
         * Editable fields from languages.
         */
        fields_languages?: ('code' | 'label')[] | null;
        /**
         * Editable fields from awards.
         */
        fields_awards?: 'name'[] | null;
        /**
         * Editable fields from programs.
         */
        fields_programs?:
          | (
              | 'programId'
              | 'slug'
              | 'titleTh'
              | 'titleEn'
              | 'programContentType'
              | 'comingSoon'
              | 'comingSoonDate'
              | 'synopsisTh'
              | 'synopsisEn'
              | 'companyProduce'
              | 'producer'
              | 'artist'
              | 'writer'
              | 'targetGroup'
              | 'programType'
              | 'genre'
              | 'subGenre'
              | 'tags'
              | 'comment'
              | 'image'
              | 'coverImage'
              | 'trailer'
              | 'video'
              | 'TrailerAirflowProxyPath'
              | 'TrailerThumbnailAirflowProxyPath'
              | 'videoAirflowProxyPath'
              | 'videoThumbnailAirflowProxyPath'
              | 'videoLink'
              | 'trailerLink'
              | 'is_IP'
              | 'is_Feature'
              | 'is_NEW'
              | 'is_Schedule'
              | 'isNewHits'
              | 'is_Award'
              | 'is_special_programs'
              | 'is_old_series'
              | 'is_continue'
              | 'is_global_programs'
              | 'is_global_international'
              | 'is_global_thai_dub'
              | 'is_normal_programs'
              | 'is_Detail'
              | 'hasSoundtrack'
              | 'hasAd'
              | 'hasCc'
              | 'hasSl'
              | 'hasBigSign'
              | 'isUncut'
              | 'firstRun'
              | 'rerunDates'
              | 'space'
              | 'format'
              | 'duration'
              | 'onThaipbs'
              | 'onAltv'
              | 'onVipa'
              | 'onFacebook'
              | 'onX'
              | 'onYoutube'
              | 'onTiktok'
              | 'views'
              | 'productionCountry'
              | 'productionYear'
              | 'rightsTerritoriesAvailable'
              | 'audioChannel1'
              | 'audioChannel2'
              | 'closeCaption1'
              | 'closeCaption2'
              | 'closeCaption3'
              | 'subtitle1'
              | 'file_type'
              | 'version'
              | 'file_ext'
              | 'is_infosheet_write'
              | 'asset_create'
              | 'asset_update'
              | 'seasons'
            )[]
          | null;
        /**
         * Editable fields from vipaPrograms.
         */
        fields_vipaPrograms?:
          | (
              | 'titleTh'
              | 'titleEn'
              | 'isNEW'
              | 'isSchedule'
              | 'isNewHits'
              | 'is_special_programs'
              | 'is_old_series'
              | 'isFeature'
              | 'is_IP'
              | 'isThaiProgram'
              | 'isInterProgram'
              | 'image'
              | 'coverImage'
              | 'vipaLink'
              | 'genre'
              | 'tags'
              | 'firstRun'
              | 'rerunDates'
              | 'duration'
              | 'hasSoundtrack'
              | 'hasAd'
              | 'hasCc'
              | 'hasSl'
              | 'hasBigSign'
              | 'isUncut'
              | 'epCount'
              | 'views'
            )[]
          | null;
        /**
         * Editable fields from seasons.
         */
        fields_seasons?:
          | (
              | 'program'
              | 'season'
              | 'seasonName'
              | 'seasonNameEn'
              | 'is_Award'
              | 'awards'
              | 'hasCc'
              | 'languages'
              | 'hasSoundtrack'
              | 'languagesSoundtrack'
              | 'comingSoon'
              | 'comingSoonDate'
              | 'synopsisTh'
              | 'synopsisEn'
              | 'coverImage'
              | 'trailer'
              | 'video'
              | 'TrailerAirflowProxyPath'
              | 'TrailerThumbnailAirflowProxyPath'
              | 'videoAirflowProxyPath'
              | 'videoThumbnailAirflowProxyPath'
              | 'videoLink'
              | 'trailerLink'
              | 'sellPricing'
              | 'episodes'
            )[]
          | null;
        /**
         * Editable fields from episodes.
         */
        fields_episodes?:
          | (
              | 'season'
              | 'ep'
              | 'epNameTh'
              | 'epNameEn'
              | 'comingSoon'
              | 'comingSoonDate'
              | 'firstRun'
              | 'rerunDates'
              | 'synopsisEpTh'
              | 'synopsisEpEn'
              | 'coverImage'
              | 'trailer'
              | 'video'
              | 'TrailerAirflowProxyPath'
              | 'TrailerThumbnailAirflowProxyPath'
              | 'videoAirflowProxyPath'
              | 'videoThumbnailAirflowProxyPath'
              | 'videoLink'
              | 'trailerLink'
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy document assignments kept for legacy data only. Collection and field permissions control access.
   */
  allowedDocuments?:
    | (
        | {
            relationTo: 'users';
            value: number | User;
          }
        | {
            relationTo: 'roleProfiles';
            value: number | RoleProfile;
          }
        | {
            relationTo: 'userGroups';
            value: number | UserGroup;
          }
        | {
            relationTo: 'media';
            value: number | Media;
          }
        | {
            relationTo: 'videos';
            value: number | Video;
          }
        | {
            relationTo: 'landing';
            value: number | Landing;
          }
        | {
            relationTo: 'trends';
            value: number | Trend;
          }
        | {
            relationTo: 'content';
            value: number | Content;
          }
        | {
            relationTo: 'header';
            value: number | Header;
          }
        | {
            relationTo: 'footer';
            value: number | Footer;
          }
        | {
            relationTo: 'languages';
            value: number | Language;
          }
        | {
            relationTo: 'awards';
            value: number | Award;
          }
        | {
            relationTo: 'programs';
            value: number | Program;
          }
        | {
            relationTo: 'vipaPrograms';
            value: number | VipaProgram;
          }
        | {
            relationTo: 'seasons';
            value: number | Season;
          }
        | {
            relationTo: 'episodes';
            value: number | Episode;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  /**
   * Program ID
   */
  programId?: string | null;
  /**
   * URL path (e.g. my-program)
   */
  slug: string;
  /**
   * Title (Thai)
   */
  titleTh?: string | null;
  /**
   * Title (English)
   */
  titleEn?: string | null;
  /**
   * Computed: titleTh or titleEn for admin list title
   */
  _displayTitle?: string | null;
  /**
   * Program content type
   */
  programContentType?: ('Series' | 'Movie') | null;
  /**
   * Categories this program belongs to
   */
  categories?: (number | Category)[] | null;
  /**
   * Coming soon
   */
  comingSoon?: boolean | null;
  /**
   * Date when this becomes available (when coming soon)
   */
  comingSoonDate?: string | null;
  /**
   * Synopsis (Thai)
   */
  synopsisTh?: string | null;
  /**
   * Synopsis (English)
   */
  synopsisEn?: string | null;
  /**
   * Company produce
   */
  companyProduce?: string | null;
  /**
   * Producer
   */
  producer?: string | null;
  /**
   * Artist
   */
  artist?: string | null;
  /**
   * Writer
   */
  writer?: string | null;
  /**
   * Program type
   */
  type?:
    | ('Short Clip' | 'Trailer' | 'PodCast' | 'Spot' | 'Filler' | 'Demo' | 'Program' | 'Picture' | 'Poster' | 'Footage')
    | null;
  /**
   * Genres
   */
  genre?: (number | Genre)[] | null;
  /**
   * Sub-genres
   */
  genre_sub?: (number | SubGenre)[] | null;
  /**
   * Tags (comma-separated or free text)
   */
  tags?: string | null;
  /**
   * Comment
   */
  comment?: string | null;
  /**
   * Image
   */
  image?: (number | null) | Media;
  /**
   * Cover image
   */
  coverImage?: (number | null) | Media;
  /**
   * Trailer video (from Videos collection)
   */
  trailer?: (number | null) | Video;
  /**
   * Main video (from Videos collection)
   */
  video?: (number | null) | Video;
  /**
   * Trailer Airflow Proxy Path
   */
  TrailerAirflowProxyPath?: string | null;
  /**
   * Trailer Thumbnail Airflow Proxy Path (same search as trailer path, saves thumbnail path)
   */
  TrailerThumbnailAirflowProxyPath?: string | null;
  /**
   * video Airflow Proxy Path
   */
  videoAirflowProxyPath?: string | null;
  /**
   * Video Thumbnail Airflow Proxy Path (same search as video path, saves thumbnail path)
   */
  videoThumbnailAirflowProxyPath?: string | null;
  /**
   * Video link (URL)
   */
  videoLink?: string | null;
  /**
   * Trailer link (URL)
   */
  trailerLink?: string | null;
  /**
   * Is IP
   */
  is_IP?: boolean | null;
  /**
   * Is Feature
   */
  is_Feature?: boolean | null;
  /**
   * Recommended
   */
  is_NEW?: boolean | null;
  /**
   * Is Schedule
   */
  is_Schedule?: boolean | null;
  /**
   * Is New Hits
   */
  isNewHits?: boolean | null;
  /**
   * Computed: checked when any season is award
   */
  is_Award?: boolean | null;
  /**
   * Is special programs
   */
  is_special_programs?: boolean | null;
  /**
   * Is old series
   */
  is_old_series?: boolean | null;
  /**
   * Is continue
   */
  is_continue?: boolean | null;
  /**
   * Is discontinued
   */
  is_discontinued?: boolean | null;
  /**
   * Is global programs
   */
  is_global_programs?: boolean | null;
  /**
   * INTERNATIONAL
   */
  is_global_international?: boolean | null;
  /**
   * Thai Dub
   */
  is_global_thai_dub?: boolean | null;
  /**
   * Is normal programs
   */
  is_normal_programs?: boolean | null;
  /**
   * Is Detail
   */
  is_Detail?: boolean | null;
  /**
   * Has soundtrack
   */
  hasSoundtrack?: boolean | null;
  /**
   * Has ad
   */
  hasAd?: boolean | null;
  /**
   * Has CC (closed captions)
   */
  hasCc?: boolean | null;
  /**
   * Has SL (sign language)
   */
  hasSl?: boolean | null;
  /**
   * Has BigSign
   */
  hasBigSign?: boolean | null;
  /**
   * Is uncut
   */
  isUncut?: boolean | null;
  /**
   * First run date and time
   */
  firstRun?: string | null;
  /**
   * Rerun dates and times (multiple allowed)
   */
  rerunDates?:
    | {
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Media Space
   */
  space?: string | null;
  /**
   * Format
   */
  format?: ('' | 'HD' | 'UHD 4K') | null;
  /**
   * Duration
   */
  duration?: number | null;
  /**
   * On ThaiPBS
   */
  onThaipbs?: boolean | null;
  /**
   * On ALTV
   */
  onAltv?: boolean | null;
  /**
   * On VIPA
   */
  onVipa?: boolean | null;
  /**
   * On Facebook
   */
  onFacebook?: boolean | null;
  /**
   * On X
   */
  onX?: boolean | null;
  /**
   * On YouTube
   */
  onYoutube?: boolean | null;
  /**
   * On TikTok
   */
  onTiktok?: boolean | null;
  /**
   * View counts per platform. Flat: { "X": 100, "Youtube": 1000 }. By month-year: { "2025-02": { "X": 100, "Youtube": 100000 }, "2025-01": { ... } }
   */
  views?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Production country
   */
  productionCountry?: string | null;
  /**
   * Production year
   */
  productionYear?: number | null;
  /**
   * Rights territories available
   */
  rightsTerritoriesAvailable?: string | null;
  /**
   * Target group age. Enter the minimum viewer age, for example 18 means older than 18.
   */
  targetGroup?: number | null;
  /**
   * Audio channel 1/2
   */
  audioChannel1_2?:
    ('' | 'Full Mix_Thai' | 'Full Mix_English' | 'Full Mix_Japanese' | 'Full Mix_Chinese' | 'Music & Effect') | null;
  /**
   * Audio channel 3/4
   */
  audioChannel3_4?:
    ('' | 'Full Mix_Thai' | 'Full Mix_English' | 'Full Mix_Japanese' | 'Full Mix_Chinese' | 'Music & Effect') | null;
  /**
   * Close caption 1
   */
  closeCaption1?: ('Thai' | 'Eng' | 'Myanmar' | 'Chinese' | 'Japan' | '') | null;
  /**
   * Close caption 2
   */
  closeCaption2?: ('Thai' | 'Eng' | 'Myanmar' | 'Chinese' | 'Japan' | '') | null;
  /**
   * Close caption 3
   */
  closeCaption3?: ('Thai' | 'Eng' | 'Myanmar' | 'Chinese' | 'Japan' | '') | null;
  /**
   * Subtitle 1
   */
  subtitle1?:
    | (
        | 'Burn Thai-Sub Into Video'
        | 'Burn Eng-Sub Into Video'
        | 'Thai-Sub Sidecar File'
        | 'Eng-Sub Sidecar File'
        | 'Interviewer Local-Sub'
        | ''
      )
    | null;
  /**
   * File type
   */
  file_type?: string | null;
  /**
   * Version
   */
  version?: number | null;
  /**
   * File extension
   */
  file_ext?: string | null;
  /**
   * Is data written from infosheet
   */
  is_infosheet_write?: boolean | null;
  /**
   * Asset create date
   */
  asset_create?: string | null;
  /**
   * Asset update date
   */
  asset_update?: string | null;
  /**
   * Seasons (for Series)
   */
  seasons?: (number | Season)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  _order?: string | null;
  /**
   * Category name
   */
  name: string;
  /**
   * URL-safe category key, e.g. news, movies, kids
   */
  slug: string;
  /**
   * Optional icon shown in navigation and category cards
   */
  icon?:
    | (
        | 'home'
        | 'search'
        | 'plus'
        | 'spark'
        | 'film'
        | 'screen'
        | 'news'
        | 'music'
        | 'food'
        | 'travel'
        | 'kids'
        | 'education'
      )
    | null;
  /**
   * Category image / poster / thumbnail
   */
  image?: (number | null) | Media;
  /**
   * Short video or GIF-style loop from Videos collection
   */
  video?: (number | null) | Video;
  /**
   * Show the header section on this category page
   */
  showHeaderSection?: boolean | null;
  /**
   * Show the category title in the header section
   */
  showTitle?: boolean | null;
  /**
   * Enable Post Room images for this category
   */
  postRoom?: boolean | null;
  /**
   * Add image groups for Post Room
   */
  postRoomGroups?:
    | {
        /**
         * Group title
         */
        title?: string | null;
        /**
         * Cover image shown before opening the group
         */
        coverImage?: (number | null) | Media;
        /**
         * Images inside this Post Room group
         */
        images?:
          | {
              /**
               * Post Room image
               */
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional URL. If set, AppShell navigation opens this link instead of the category page.
   */
  link?: string | null;
  /**
   * Legacy numeric order. Use drag-and-drop on the Categories list to change display order.
   */
  order?: number | null;
  /**
   * Show this category in brand tiles
   */
  isActive?: boolean | null;
  /**
   * Show this category in the AppShell navigation
   */
  appShellActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Title for the media
   */
  title?: string | null;
  /**
   * Alt text for the image
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  /**
   * Title for the video
   */
  title?: string | null;
  /**
   * Alt text / description for the video (accessibility)
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Reusable genre names for programs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: number;
  /**
   * Genre name
   */
  name: string;
  /**
   * URL-safe genre key, e.g. documentary
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable sub-genre names. A sub-genre may optionally belong to a genre.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subGenres".
 */
export interface SubGenre {
  id: number;
  /**
   * Sub-genre name
   */
  name: string;
  /**
   * URL-safe sub-genre key, e.g. science-technology
   */
  slug: string;
  /**
   * Optional parent genre
   */
  genre?: (number | null) | Genre;
  updatedAt: string;
  createdAt: string;
}
/**
 * Programs > Seasons
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  /**
   * Parent program
   */
  program: number | Program;
  /**
   * Season number
   */
  season?: number | null;
  /**
   * Season name (Thai)
   */
  seasonName?: string | null;
  /**
   * Season name (English)
   */
  seasonNameEn?: string | null;
  /**
   * Is Award
   */
  is_Award?: boolean | null;
  /**
   * Awards received by this season
   */
  awards?:
    | {
        /**
         * Award name
         */
        awardName?: (number | null) | Award;
        /**
         * Year received
         */
        awardYear: number;
        /**
         * Award detail
         */
        awardDetail?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Updated date/time for this award row
         */
        awardUpdatedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Has CC (closed captions)
   */
  hasCc?: boolean | null;
  /**
   * CC languages supported (multi-select dropdown)
   */
  languages?: (number | Language)[] | null;
  /**
   * Has soundtrack
   */
  hasSoundtrack?: boolean | null;
  /**
   * Soundtrack languages supported (multi-select dropdown)
   */
  languagesSoundtrack?: (number | Language)[] | null;
  /**
   * Coming soon
   */
  comingSoon?: boolean | null;
  /**
   * Date when this becomes available (when coming soon)
   */
  comingSoonDate?: string | null;
  /**
   * Synopsis (Thai)
   */
  synopsisTh?: string | null;
  /**
   * Synopsis (English)
   */
  synopsisEn?: string | null;
  /**
   * Cover image
   */
  coverImage?: (number | null) | Media;
  /**
   * Trailer video (from Videos collection)
   */
  trailer?: (number | null) | Video;
  /**
   * Main video (from Videos collection)
   */
  video?: (number | null) | Video;
  /**
   * Trailer Airflow Proxy Path
   */
  TrailerAirflowProxyPath?: string | null;
  /**
   * Trailer Thumbnail Airflow Proxy Path (same search as trailer path, saves thumbnail path)
   */
  TrailerThumbnailAirflowProxyPath?: string | null;
  /**
   * video Airflow Proxy Path
   */
  videoAirflowProxyPath?: string | null;
  /**
   * Video Thumbnail Airflow Proxy Path (same search as video path, saves thumbnail path)
   */
  videoThumbnailAirflowProxyPath?: string | null;
  /**
   * Video link (URL)
   */
  videoLink?: string | null;
  /**
   * Trailer link (URL)
   */
  trailerLink?: string | null;
  /**
   * One-to-one sell price settings for this season. Use Ready for Sale only when the parent program is IP.
   */
  sellPricing?: {
    /**
     * Show this season as ready for sale. This is allowed only when the parent program is IP.
     */
    readyForSale?: boolean | null;
    /**
     * Set one sell price per video format.
     */
    formatPrices?:
      | {
          format: 'HD' | 'UHD 4K';
          /**
           * Sell price for this format.
           */
          price: number;
          id?: string | null;
        }[]
      | null;
    /**
     * This sell package includes closed captions.
     */
    hasCc?: boolean | null;
    /**
     * Set an extra or included price for each CC language.
     */
    ccLanguagePrices?:
      | {
          /**
           * CC language.
           */
          language: number | Language;
          /**
           * Price for this CC language.
           */
          price: number;
          id?: string | null;
        }[]
      | null;
    /**
     * This sell package includes AD.
     */
    hasAd?: boolean | null;
    /**
     * Price when AD is included.
     */
    adPrice?: number | null;
  };
  /**
   * Computed: Season label for admin list
   */
  _displayTitle?: string | null;
  /**
   * Episodes in this season
   */
  episodes?: (number | Episode)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Award names that can be selected in program seasons.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  /**
   * Award name
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Language list (used as multi-select dropdown in seasons).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages".
 */
export interface Language {
  id: number;
  /**
   * Short code (e.g. th, en, my)
   */
  code: string;
  /**
   * Display label (optional, e.g. Thai, English)
   */
  label?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Programs > Seasons > Episodes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes".
 */
export interface Episode {
  id: number;
  /**
   * Parent season
   */
  season: number | Season;
  /**
   * Episode number or code
   */
  ep?: number | null;
  /**
   * Episode name (Thai)
   */
  epNameTh?: string | null;
  /**
   * Episode name (English)
   */
  epNameEn?: string | null;
  /**
   * Coming soon
   */
  comingSoon?: boolean | null;
  /**
   * Date when this becomes available (when coming soon)
   */
  comingSoonDate?: string | null;
  /**
   * First run date and time
   */
  firstRun?: string | null;
  /**
   * Rerun dates and times (multiple allowed)
   */
  rerunDates?:
    | {
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Episode synopsis (Thai)
   */
  synopsisEpTh?: string | null;
  /**
   * Episode synopsis (English)
   */
  synopsisEpEn?: string | null;
  /**
   * Cover image
   */
  coverImage?: (number | null) | Media;
  /**
   * Trailer video (from Videos collection)
   */
  trailer?: (number | null) | Video;
  /**
   * Main video (from Videos collection)
   */
  video?: (number | null) | Video;
  /**
   * Trailer Airflow Proxy Path
   */
  TrailerAirflowProxyPath?: string | null;
  /**
   * Trailer Thumbnail Airflow Proxy Path (same search as trailer path, saves thumbnail path)
   */
  TrailerThumbnailAirflowProxyPath?: string | null;
  /**
   * video Airflow Proxy Path
   */
  videoAirflowProxyPath?: string | null;
  /**
   * Video Thumbnail Airflow Proxy Path (same search as video path, saves thumbnail path)
   */
  videoThumbnailAirflowProxyPath?: string | null;
  /**
   * Video link (URL)
   */
  videoLink?: string | null;
  /**
   * Trailer link (URL)
   */
  trailerLink?: string | null;
  /**
   * Computed: E{ep} - name for admin list
   */
  _displayTitle?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vipaPrograms".
 */
export interface VipaProgram {
  id: number;
  /**
   * Title (Thai)
   */
  titleTh?: string | null;
  /**
   * Title (English)
   */
  titleEn?: string | null;
  /**
   * Computed: titleTh or titleEn for admin list title
   */
  _displayTitle?: string | null;
  /**
   * Is NEW
   */
  isNEW?: boolean | null;
  /**
   * Is Schedule
   */
  isSchedule?: boolean | null;
  /**
   * Is New Hits
   */
  isNewHits?: boolean | null;
  /**
   * Is special programs
   */
  is_special_programs?: boolean | null;
  /**
   * Is old series
   */
  is_old_series?: boolean | null;
  /**
   * Is Feature
   */
  isFeature?: boolean | null;
  /**
   * Is IP
   */
  is_IP?: boolean | null;
  /**
   * Is Thai program
   */
  isThaiProgram?: boolean | null;
  /**
   * Is inter program
   */
  isInterProgram?: boolean | null;
  /**
   * Image
   */
  image?: (number | null) | Media;
  /**
   * Cover image
   */
  coverImage?: (number | null) | Media;
  /**
   * VIPA link (URL)
   */
  vipaLink?: string | null;
  /**
   * Genre
   */
  genre?:
    | (
        | 'Drama&Sitcom'
        | 'Variety&Lifestyle'
        | 'Documentary'
        | 'News&Facture'
        | 'Music'
        | 'Special Program'
        | 'Food&Travel'
        | 'Kids&Family'
        | 'Animation'
      )
    | null;
  /**
   * Tags (comma-separated or free text)
   */
  tags?: string | null;
  /**
   * First run date and time
   */
  firstRun?: string | null;
  /**
   * Rerun dates and times (multiple allowed)
   */
  rerunDates?:
    | {
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Duration
   */
  duration?: number | null;
  /**
   * Has soundtrack
   */
  hasSoundtrack?: boolean | null;
  /**
   * Has ad
   */
  hasAd?: boolean | null;
  /**
   * Has CC (closed captions)
   */
  hasCc?: boolean | null;
  /**
   * Has SL (sign language)
   */
  hasSl?: boolean | null;
  /**
   * Has BigSign
   */
  hasBigSign?: boolean | null;
  /**
   * Is uncut
   */
  isUncut?: boolean | null;
  /**
   * Number of episodes
   */
  epCount?: number | null;
  /**
   * View counts per platform. Flat: { "view": 100, "views": 1000, "other": 10000 }. By month-year: { "2025-02": { "view": 100 }, "2025-01": { } }
   */
  views?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Landing page settings (hero background image).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing".
 */
export interface Landing {
  id: number;
  /**
   * Label for this settings document (e.g. "Landing")
   */
  title: string;
  /**
   * Background image for the landing page (one per row; multiple rows = loop)
   */
  heroImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Trending items (image + title + link). Image required for Others only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trends".
 */
export interface Trend {
  id: number;
  /**
   * Social platform. Image is required only for Others.
   */
  type: 'facebook' | 'youtube' | 'instagram' | 'tiktok' | 'x' | 'others';
  /**
   * Trend title
   */
  title?: string | null;
  /**
   * Destination URL
   */
  link: string;
  /**
   * Trend image (from Media). Required for Others only.
   */
  image?: (number | null) | Media;
  /**
   * Height of the trend box in pixels. Leave empty for default (auto height).
   */
  boxHeight?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Content with Thai/English titles and topic sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content".
 */
export interface Content {
  id: number;
  /**
   * URL path (e.g. topic). Used in /content/[slug]. Leave empty to use ID in URL.
   */
  slug?: string | null;
  /**
   * Title (Thai)
   */
  titleTh?: string | null;
  /**
   * Title (English)
   */
  titleEn?: string | null;
  /**
   * Addable topic blocks (Topic + Content per language)
   */
  topicSections?:
    | {
        /**
         * Topic (Thai)
         */
        topicTh?: string | null;
        /**
         * Topic (English)
         */
        topicEn?: string | null;
        /**
         * Content (Thai)
         */
        contentTh?: string | null;
        /**
         * Content (English)
         */
        contentEn?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Main content (Thai)
   */
  contentTh?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Main content (English)
   */
  contentEn?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Header with title and multiple items (link or content).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Title (Thai)
   */
  titleTh?: string | null;
  /**
   * Title (English)
   */
  titleEn?: string | null;
  /**
   * Header items: each row is either a link or a content from the Content collection.
   */
  items?:
    | {
        /**
         * Choose Link or Content
         */
        itemType: 'link' | 'content';
        /**
         * URL for the link (e.g. https://... or /path)
         */
        linkUrl?: string | null;
        /**
         * Link label (Thai)
         */
        linkLabelTh?: string | null;
        /**
         * Link label (English)
         */
        linkLabelEn?: string | null;
        /**
         * Select a Content document
         */
        content?: (number | null) | Content;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Footer with title and multiple items (link or content).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Title (Thai)
   */
  titleTh?: string | null;
  /**
   * Title (English)
   */
  titleEn?: string | null;
  /**
   * Footer items: each row is either a link or a content from the Content collection.
   */
  items?:
    | {
        /**
         * Choose Link or Content
         */
        itemType: 'link' | 'content';
        /**
         * URL for the link (e.g. https://... or /path)
         */
        linkUrl?: string | null;
        /**
         * Link label (Thai)
         */
        linkLabelTh?: string | null;
        /**
         * Link label (English)
         */
        linkLabelEn?: string | null;
        /**
         * Select a Content document
         */
        content?: (number | null) | Content;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Homepage hero slides shown before program-generated hero slides.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroImages".
 */
export interface HeroImage {
  id: number;
  _order?: string | null;
  /**
   * Main hero title
   */
  title: string;
  /**
   * Small label above the title, e.g. ThaiPBS Category
   */
  eyebrow?: string | null;
  /**
   * Hero background image
   */
  image: number | Media;
  /**
   * Year or short date label shown in the metadata line
   */
  year?: string | null;
  /**
   * Rating label, e.g. ALL Age, 13+, 18+
   */
  rating?: string | null;
  /**
   * Duration label, e.g. 48m, Series, Movie
   */
  duration?: string | null;
  /**
   * Hero synopsis text
   */
  description?: string | null;
  /**
   * Genres shown below synopsis
   */
  genre?: (number | Genre)[] | null;
  /**
   * Sub-genres shown below synopsis
   */
  subGenre?: (number | SubGenre)[] | null;
  /**
   * Show left side shadow and text details
   */
  showDetails?: boolean | null;
  /**
   * Show this slide on the homepage hero
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roleProfiles';
        value: number | RoleProfile;
      } | null)
    | ({
        relationTo: 'userGroups';
        value: number | UserGroup;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'landing';
        value: number | Landing;
      } | null)
    | ({
        relationTo: 'trends';
        value: number | Trend;
      } | null)
    | ({
        relationTo: 'content';
        value: number | Content;
      } | null)
    | ({
        relationTo: 'header';
        value: number | Header;
      } | null)
    | ({
        relationTo: 'footer';
        value: number | Footer;
      } | null)
    | ({
        relationTo: 'languages';
        value: number | Language;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'genres';
        value: number | Genre;
      } | null)
    | ({
        relationTo: 'subGenres';
        value: number | SubGenre;
      } | null)
    | ({
        relationTo: 'heroImages';
        value: number | HeroImage;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'vipaPrograms';
        value: number | VipaProgram;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'episodes';
        value: number | Episode;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  roles?: T;
  groups?: T;
  ownedPrograms?: T;
  ownedVipaPrograms?: T;
  allowedAdminPages?: T;
  collectionPermissions?:
    | T
    | {
        collection?: T;
        operations?: T;
        id?: T;
      };
  fieldPermissions?:
    | T
    | {
        collection?: T;
        allFields?: T;
        fields?: T;
        fields_users?: T;
        fields_roleProfiles?: T;
        fields_userGroups?: T;
        fields_media?: T;
        fields_videos?: T;
        fields_landing?: T;
        fields_trends?: T;
        fields_content?: T;
        fields_header?: T;
        fields_footer?: T;
        fields_languages?: T;
        fields_awards?: T;
        fields_programs?: T;
        fields_vipaPrograms?: T;
        fields_seasons?: T;
        fields_episodes?: T;
        id?: T;
      };
  allowedDocuments?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roleProfiles_select".
 */
export interface RoleProfilesSelect<T extends boolean = true> {
  name?: T;
  users?: T;
  allowedAdminPages?: T;
  collectionPermissions?:
    | T
    | {
        collection?: T;
        operations?: T;
        id?: T;
      };
  fieldPermissions?:
    | T
    | {
        collection?: T;
        allFields?: T;
        fields?: T;
        fields_users?: T;
        fields_roleProfiles?: T;
        fields_userGroups?: T;
        fields_media?: T;
        fields_videos?: T;
        fields_landing?: T;
        fields_trends?: T;
        fields_content?: T;
        fields_header?: T;
        fields_footer?: T;
        fields_languages?: T;
        fields_awards?: T;
        fields_programs?: T;
        fields_vipaPrograms?: T;
        fields_seasons?: T;
        fields_episodes?: T;
        id?: T;
      };
  allowedDocuments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userGroups_select".
 */
export interface UserGroupsSelect<T extends boolean = true> {
  name?: T;
  users?: T;
  ownedPrograms?: T;
  ownedVipaPrograms?: T;
  allowedAdminPages?: T;
  collectionPermissions?:
    | T
    | {
        collection?: T;
        operations?: T;
        id?: T;
      };
  fieldPermissions?:
    | T
    | {
        collection?: T;
        allFields?: T;
        fields?: T;
        fields_users?: T;
        fields_roleProfiles?: T;
        fields_userGroups?: T;
        fields_media?: T;
        fields_videos?: T;
        fields_landing?: T;
        fields_trends?: T;
        fields_content?: T;
        fields_header?: T;
        fields_footer?: T;
        fields_languages?: T;
        fields_awards?: T;
        fields_programs?: T;
        fields_vipaPrograms?: T;
        fields_seasons?: T;
        fields_episodes?: T;
        id?: T;
      };
  allowedDocuments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_select".
 */
export interface LandingSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trends_select".
 */
export interface TrendsSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  link?: T;
  image?: T;
  boxHeight?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content_select".
 */
export interface ContentSelect<T extends boolean = true> {
  slug?: T;
  titleTh?: T;
  titleEn?: T;
  topicSections?:
    | T
    | {
        topicTh?: T;
        topicEn?: T;
        contentTh?: T;
        contentEn?: T;
        id?: T;
      };
  contentTh?: T;
  contentEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  titleTh?: T;
  titleEn?: T;
  items?:
    | T
    | {
        itemType?: T;
        linkUrl?: T;
        linkLabelTh?: T;
        linkLabelEn?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  titleTh?: T;
  titleEn?: T;
  items?:
    | T
    | {
        itemType?: T;
        linkUrl?: T;
        linkLabelTh?: T;
        linkLabelEn?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages_select".
 */
export interface LanguagesSelect<T extends boolean = true> {
  code?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  icon?: T;
  image?: T;
  video?: T;
  showHeaderSection?: T;
  showTitle?: T;
  postRoom?: T;
  postRoomGroups?:
    | T
    | {
        title?: T;
        coverImage?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        id?: T;
      };
  link?: T;
  order?: T;
  isActive?: T;
  appShellActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subGenres_select".
 */
export interface SubGenresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  genre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "heroImages_select".
 */
export interface HeroImagesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  eyebrow?: T;
  image?: T;
  year?: T;
  rating?: T;
  duration?: T;
  description?: T;
  genre?: T;
  subGenre?: T;
  showDetails?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  programId?: T;
  slug?: T;
  titleTh?: T;
  titleEn?: T;
  _displayTitle?: T;
  programContentType?: T;
  categories?: T;
  comingSoon?: T;
  comingSoonDate?: T;
  synopsisTh?: T;
  synopsisEn?: T;
  companyProduce?: T;
  producer?: T;
  artist?: T;
  writer?: T;
  type?: T;
  genre?: T;
  genre_sub?: T;
  tags?: T;
  comment?: T;
  image?: T;
  coverImage?: T;
  trailer?: T;
  video?: T;
  TrailerAirflowProxyPath?: T;
  TrailerThumbnailAirflowProxyPath?: T;
  videoAirflowProxyPath?: T;
  videoThumbnailAirflowProxyPath?: T;
  videoLink?: T;
  trailerLink?: T;
  is_IP?: T;
  is_Feature?: T;
  is_NEW?: T;
  is_Schedule?: T;
  isNewHits?: T;
  is_Award?: T;
  is_special_programs?: T;
  is_old_series?: T;
  is_continue?: T;
  is_discontinued?: T;
  is_global_programs?: T;
  is_global_international?: T;
  is_global_thai_dub?: T;
  is_normal_programs?: T;
  is_Detail?: T;
  hasSoundtrack?: T;
  hasAd?: T;
  hasCc?: T;
  hasSl?: T;
  hasBigSign?: T;
  isUncut?: T;
  firstRun?: T;
  rerunDates?:
    | T
    | {
        date?: T;
        id?: T;
      };
  space?: T;
  format?: T;
  duration?: T;
  onThaipbs?: T;
  onAltv?: T;
  onVipa?: T;
  onFacebook?: T;
  onX?: T;
  onYoutube?: T;
  onTiktok?: T;
  views?: T;
  productionCountry?: T;
  productionYear?: T;
  rightsTerritoriesAvailable?: T;
  targetGroup?: T;
  audioChannel1_2?: T;
  audioChannel3_4?: T;
  closeCaption1?: T;
  closeCaption2?: T;
  closeCaption3?: T;
  subtitle1?: T;
  file_type?: T;
  version?: T;
  file_ext?: T;
  is_infosheet_write?: T;
  asset_create?: T;
  asset_update?: T;
  seasons?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vipaPrograms_select".
 */
export interface VipaProgramsSelect<T extends boolean = true> {
  titleTh?: T;
  titleEn?: T;
  _displayTitle?: T;
  isNEW?: T;
  isSchedule?: T;
  isNewHits?: T;
  is_special_programs?: T;
  is_old_series?: T;
  isFeature?: T;
  is_IP?: T;
  isThaiProgram?: T;
  isInterProgram?: T;
  image?: T;
  coverImage?: T;
  vipaLink?: T;
  genre?: T;
  tags?: T;
  firstRun?: T;
  rerunDates?:
    | T
    | {
        date?: T;
        id?: T;
      };
  duration?: T;
  hasSoundtrack?: T;
  hasAd?: T;
  hasCc?: T;
  hasSl?: T;
  hasBigSign?: T;
  isUncut?: T;
  epCount?: T;
  views?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  program?: T;
  season?: T;
  seasonName?: T;
  seasonNameEn?: T;
  is_Award?: T;
  awards?:
    | T
    | {
        awardName?: T;
        awardYear?: T;
        awardDetail?: T;
        awardUpdatedAt?: T;
        id?: T;
      };
  hasCc?: T;
  languages?: T;
  hasSoundtrack?: T;
  languagesSoundtrack?: T;
  comingSoon?: T;
  comingSoonDate?: T;
  synopsisTh?: T;
  synopsisEn?: T;
  coverImage?: T;
  trailer?: T;
  video?: T;
  TrailerAirflowProxyPath?: T;
  TrailerThumbnailAirflowProxyPath?: T;
  videoAirflowProxyPath?: T;
  videoThumbnailAirflowProxyPath?: T;
  videoLink?: T;
  trailerLink?: T;
  sellPricing?:
    | T
    | {
        readyForSale?: T;
        formatPrices?:
          | T
          | {
              format?: T;
              price?: T;
              id?: T;
            };
        hasCc?: T;
        ccLanguagePrices?:
          | T
          | {
              language?: T;
              price?: T;
              id?: T;
            };
        hasAd?: T;
        adPrice?: T;
      };
  _displayTitle?: T;
  episodes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes_select".
 */
export interface EpisodesSelect<T extends boolean = true> {
  season?: T;
  ep?: T;
  epNameTh?: T;
  epNameEn?: T;
  comingSoon?: T;
  comingSoonDate?: T;
  firstRun?: T;
  rerunDates?:
    | T
    | {
        date?: T;
        id?: T;
      };
  synopsisEpTh?: T;
  synopsisEpEn?: T;
  coverImage?: T;
  trailer?: T;
  video?: T;
  TrailerAirflowProxyPath?: T;
  TrailerThumbnailAirflowProxyPath?: T;
  videoAirflowProxyPath?: T;
  videoThumbnailAirflowProxyPath?: T;
  videoLink?: T;
  trailerLink?: T;
  _displayTitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}