import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "pavillions"."enum_users_field_permissions_fields_programs" ADD VALUE 'producers' BEFORE 'producer';
  ALTER TYPE "pavillions"."enum_users_field_permissions_fields_programs" ADD VALUE 'directors' BEFORE 'producer';
  ALTER TYPE "pavillions"."enum_users_field_permissions_fields_programs" ADD VALUE 'artists' BEFORE 'producer';
  ALTER TYPE "pavillions"."enum_users_field_permissions_fields_programs" ADD VALUE 'writers' BEFORE 'producer';
  ALTER TYPE "pavillions"."enum_role_profiles_field_permissions_fields_programs" ADD VALUE 'producers' BEFORE 'producer';
  ALTER TYPE "pavillions"."enum_role_profiles_field_permissions_fields_programs" ADD VALUE 'directors' BEFORE 'producer';
  ALTER TYPE "pavillions"."enum_role_profiles_field_permissions_fields_programs" ADD VALUE 'artists' BEFORE 'producer';
  ALTER TYPE "pavillions"."enum_role_profiles_field_permissions_fields_programs" ADD VALUE 'writers' BEFORE 'producer';
  ALTER TYPE "pavillions"."enum_user_groups_field_permissions_fields_programs" ADD VALUE 'producers' BEFORE 'producer';
  ALTER TYPE "pavillions"."enum_user_groups_field_permissions_fields_programs" ADD VALUE 'directors' BEFORE 'producer';
  ALTER TYPE "pavillions"."enum_user_groups_field_permissions_fields_programs" ADD VALUE 'artists' BEFORE 'producer';
  ALTER TYPE "pavillions"."enum_user_groups_field_permissions_fields_programs" ADD VALUE 'writers' BEFORE 'producer';`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pavillions"."users_field_permissions_fields_programs" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "pavillions"."enum_users_field_permissions_fields_programs";
  CREATE TYPE "pavillions"."enum_users_field_permissions_fields_programs" AS ENUM('programId', 'slug', 'titleTh', 'titleEn', 'programContentType', 'comingSoon', 'comingSoonDate', 'synopsisTh', 'synopsisEn', 'companyProduce', 'companyProduceEn', 'producer', 'producerEn', 'director', 'directorEn', 'artist', 'artistEn', 'writer', 'writerEn', 'targetGroup', 'programType', 'genre', 'subGenre', 'tags', 'comment', 'image', 'coverImage', 'trailer', 'video', 'TrailerAirflowProxyPath', 'TrailerThumbnailAirflowProxyPath', 'videoAirflowProxyPath', 'videoThumbnailAirflowProxyPath', 'videoLink', 'trailerLink', 'is_IP', 'is_Feature', 'is_NEW', 'is_Schedule', 'isNewHits', 'is_Award', 'is_special_programs', 'is_old_series', 'is_continue', 'is_global_programs', 'is_global_international', 'is_global_thai_dub', 'is_normal_programs', 'is_Detail', 'hasSoundtrack', 'hasAd', 'hasCc', 'hasSl', 'hasBigSign', 'isUncut', 'firstRun', 'rerunDates', 'space', 'format', 'duration', 'onThaipbs', 'onAltv', 'onVipa', 'onFacebook', 'onX', 'onYoutube', 'onTiktok', 'views', 'productionCountry', 'productionYear', 'rightsTerritoriesAvailable', 'audioChannel1', 'audioChannel2', 'closeCaption1', 'closeCaption2', 'closeCaption3', 'subtitle1', 'file_type', 'version', 'file_ext', 'is_infosheet_write', 'asset_create', 'asset_update', 'seasons');
  ALTER TABLE "pavillions"."users_field_permissions_fields_programs" ALTER COLUMN "value" SET DATA TYPE "pavillions"."enum_users_field_permissions_fields_programs" USING "value"::"pavillions"."enum_users_field_permissions_fields_programs";
  ALTER TABLE "pavillions"."role_profiles_field_permissions_fields_programs" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "pavillions"."enum_role_profiles_field_permissions_fields_programs";
  CREATE TYPE "pavillions"."enum_role_profiles_field_permissions_fields_programs" AS ENUM('programId', 'slug', 'titleTh', 'titleEn', 'programContentType', 'comingSoon', 'comingSoonDate', 'synopsisTh', 'synopsisEn', 'companyProduce', 'companyProduceEn', 'producer', 'producerEn', 'director', 'directorEn', 'artist', 'artistEn', 'writer', 'writerEn', 'targetGroup', 'programType', 'genre', 'subGenre', 'tags', 'comment', 'image', 'coverImage', 'trailer', 'video', 'TrailerAirflowProxyPath', 'TrailerThumbnailAirflowProxyPath', 'videoAirflowProxyPath', 'videoThumbnailAirflowProxyPath', 'videoLink', 'trailerLink', 'is_IP', 'is_Feature', 'is_NEW', 'is_Schedule', 'isNewHits', 'is_Award', 'is_special_programs', 'is_old_series', 'is_continue', 'is_global_programs', 'is_global_international', 'is_global_thai_dub', 'is_normal_programs', 'is_Detail', 'hasSoundtrack', 'hasAd', 'hasCc', 'hasSl', 'hasBigSign', 'isUncut', 'firstRun', 'rerunDates', 'space', 'format', 'duration', 'onThaipbs', 'onAltv', 'onVipa', 'onFacebook', 'onX', 'onYoutube', 'onTiktok', 'views', 'productionCountry', 'productionYear', 'rightsTerritoriesAvailable', 'audioChannel1', 'audioChannel2', 'closeCaption1', 'closeCaption2', 'closeCaption3', 'subtitle1', 'file_type', 'version', 'file_ext', 'is_infosheet_write', 'asset_create', 'asset_update', 'seasons');
  ALTER TABLE "pavillions"."role_profiles_field_permissions_fields_programs" ALTER COLUMN "value" SET DATA TYPE "pavillions"."enum_role_profiles_field_permissions_fields_programs" USING "value"::"pavillions"."enum_role_profiles_field_permissions_fields_programs";
  ALTER TABLE "pavillions"."user_groups_field_permissions_fields_programs" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "pavillions"."enum_user_groups_field_permissions_fields_programs";
  CREATE TYPE "pavillions"."enum_user_groups_field_permissions_fields_programs" AS ENUM('programId', 'slug', 'titleTh', 'titleEn', 'programContentType', 'comingSoon', 'comingSoonDate', 'synopsisTh', 'synopsisEn', 'companyProduce', 'companyProduceEn', 'producer', 'producerEn', 'director', 'directorEn', 'artist', 'artistEn', 'writer', 'writerEn', 'targetGroup', 'programType', 'genre', 'subGenre', 'tags', 'comment', 'image', 'coverImage', 'trailer', 'video', 'TrailerAirflowProxyPath', 'TrailerThumbnailAirflowProxyPath', 'videoAirflowProxyPath', 'videoThumbnailAirflowProxyPath', 'videoLink', 'trailerLink', 'is_IP', 'is_Feature', 'is_NEW', 'is_Schedule', 'isNewHits', 'is_Award', 'is_special_programs', 'is_old_series', 'is_continue', 'is_global_programs', 'is_global_international', 'is_global_thai_dub', 'is_normal_programs', 'is_Detail', 'hasSoundtrack', 'hasAd', 'hasCc', 'hasSl', 'hasBigSign', 'isUncut', 'firstRun', 'rerunDates', 'space', 'format', 'duration', 'onThaipbs', 'onAltv', 'onVipa', 'onFacebook', 'onX', 'onYoutube', 'onTiktok', 'views', 'productionCountry', 'productionYear', 'rightsTerritoriesAvailable', 'audioChannel1', 'audioChannel2', 'closeCaption1', 'closeCaption2', 'closeCaption3', 'subtitle1', 'file_type', 'version', 'file_ext', 'is_infosheet_write', 'asset_create', 'asset_update', 'seasons');
  ALTER TABLE "pavillions"."user_groups_field_permissions_fields_programs" ALTER COLUMN "value" SET DATA TYPE "pavillions"."enum_user_groups_field_permissions_fields_programs" USING "value"::"pavillions"."enum_user_groups_field_permissions_fields_programs";`)
}
