"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef } from "react";
import { titleInlineText, type Title } from "@/lib/content";
import type { CategoryTile, TitleCollections } from "@/lib/payload-content";
import { getPrototypeCategories, titleCategories, type PrototypeCategory } from "./blog-data";

type HomeProps = { categoryTiles: CategoryTile[]; collections: TitleCollections; titles: Title[] };
type CategoryProps = { category: PrototypeCategory; titles: Title[] };
type ArticleProps = { related: Title[]; title: Title };

export function StyleTenHome({ categoryTiles, collections, titles }: HomeProps) {
  const available = titles.filter((item) => !item.isDiscontinued);
  const lead = collections.heroes[0] ?? available.find((item) => item.featured) ?? available[0];
  const fresh = unique([...available.filter((item) => item.isNew), ...available]).filter((item) => item.slug !== lead?.slug).slice(0, 6);
  const recommended = unique([...collections.recommended, ...available]).slice(0, 8);
  const latest = unique([...collections.continueWatching, ...available]).slice(0, 7);
  const playlists = playlistSections(collections).slice(0, 4);
  return <StyleTenMotion><div className="s10-shell" id="top"><StyleTenHeader categories={getPrototypeCategories(titles)} /><main>
    {lead ? <VlogHero title={lead} /> : null}
    <section className="s10-intro" data-s10-reveal><p>Thai PBS, ready to watch</p><h2>Stories move differently<br />when you can step inside.</h2><span>ค้นพบรายการเด่น เรื่องราวใหม่ และเพลย์ลิสต์ที่คัดสรรจากคลัง Thai PBS</span><a href="#new">Start watching ↓</a></section>
    <VideoGrid titles={fresh} />
    <PlaylistStage playlists={playlists} />
    <RecommendationRail titles={recommended} />
    <Trending titles={recommended.slice(0, 5)} />
    <Discover categories={categoryTiles} />
    <LatestList titles={latest} />
  </main><StyleTenFooter categories={getPrototypeCategories(titles)} /></div></StyleTenMotion>;
}

export function StyleTenCategory({ category, titles }: CategoryProps) { return <StyleTenMotion><div className="s10-shell s10-inner"><StyleTenHeader categories={getPrototypeCategories(titles)} /><main><header className="s10-index-head" data-s10-reveal><p>Playlist / Thai PBS</p><h1>{category.label}</h1><span>{titles.length} programs ready to explore</span></header><section className="s10-index-grid">{titles.map((title, index) => <VideoCard index={index} key={title.slug} title={title} />)}</section></main><StyleTenFooter categories={getPrototypeCategories(titles)} /></div></StyleTenMotion>; }
export function StyleTenArticle({ related, title }: ArticleProps) { const category = titleCategories(title)[0]; return <StyleTenMotion><div className="s10-shell s10-inner"><StyleTenHeader categories={getPrototypeCategories([title,...related])} /><main><article className="s10-article"><div className="s10-article__visual"><VideoImage priority title={title} /><PlayMark label="Watch program" /></div><header data-s10-reveal><p>{category.label} / {title.type}</p><h1>{titleInlineText(title)}</h1><span>{[title.year,title.duration,title.rating].filter(Boolean).join(" · ")}</span></header><div className="s10-article__body"><p>{title.description}</p><dl><div><dt>Category</dt><dd>{category.label}</dd></div><div><dt>Format</dt><dd>{title.type}</dd></div><div><dt>Duration</dt><dd>{title.duration || "—"}</dd></div></dl></div></article>{related.length ? <section className="s10-related"><BigLabel label="next" /><div>{related.slice(0,4).map((item,index)=><VideoCard index={index} key={item.slug} title={item}/>)}</div></section>:null}</main><StyleTenFooter categories={getPrototypeCategories([title,...related])} /></div></StyleTenMotion>; }

function StyleTenMotion({ children }: { children: React.ReactNode }) { const root=useRef<HTMLDivElement>(null); useEffect(()=>{const element=root.current;if(!element)return;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const header=element.querySelector<HTMLElement>(".s10-header");const onScroll=()=>header?.classList.toggle("is-scrolled",scrollY>70);onScroll();addEventListener("scroll",onScroll,{passive:true});if(reduced)return()=>removeEventListener("scroll",onScroll);const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target);}}),{threshold:.12,rootMargin:"0px 0px -7%"});element.querySelectorAll<HTMLElement>("[data-s10-reveal]").forEach(item=>observer.observe(item));return()=>{removeEventListener("scroll",onScroll);observer.disconnect();};},[]);return <div className="style-ten" ref={root}>{children}</div>; }
function StyleTenHeader({ categories }: { categories: PrototypeCategory[] }) { return <header className="s10-header"><Link className="s10-brand" href="/prototype/style-10"><b>THAIPBS</b><span>/PLAY</span></Link><nav><a href="#new">New</a><a href="#playlists">Playlists</a><a href="#popular">Popular</a><a href="#discover">Discover</a></nav><details><summary aria-label="Open menu"><span>Menu</span><b>＋</b></summary><div><a href="#new">New</a><a href="#playlists">Playlists</a><a href="#popular">Popular</a>{categories.slice(0,5).map(item=><Link href={`/prototype/style-10/category/${item.slug}`} key={item.slug}>{item.label}</Link>)}</div></details></header>; }
function VlogHero({ title }: { title: Title }) { return <section className="s10-hero"><Link href={`/prototype/style-10/article/${title.slug}`}><VideoImage priority title={title} /><div className="s10-hero__shade"/><div className="s10-hero__copy" data-s10-reveal><p>{titleCategories(title)[0]?.label} · {title.duration || title.type}</p><h1>{titleInlineText(title)}</h1><PlayMark label="Watch now" /></div></Link></section>; }
function VideoGrid({ titles }: { titles: Title[] }) { if(!titles.length)return null;return <section className="s10-new" id="new"><BigLabel label="new" /><div>{titles.map((title,index)=><VideoCard index={index} key={title.slug} title={title}/>)}</div></section>; }
function PlaylistStage({ playlists }: { playlists:Array<{id:string;title:string;titles:Title[]}> }) { if(!playlists.length)return null;return <section className="s10-playlists" id="playlists"><BigLabel label="watch" />{playlists.map((playlist,index)=>{const lead=playlist.titles[0];if(!lead)return null;return <article className={`s10-playlist s10-playlist--${index%2}`} key={playlist.id} data-s10-reveal><div className="s10-playlist__copy"><p>Playlist {String(index+1).padStart(2,"0")}</p><h2>{playlist.title}</h2><span>{lead.description}</span><Link href={`/prototype/style-10/article/${lead.slug}`}>View playlist →</Link></div><Link className="s10-playlist__video" href={`/prototype/style-10/article/${lead.slug}`}><VideoImage title={lead}/><PlayMark label="Play" /></Link><div className="s10-playlist__queue">{playlist.titles.slice(1,4).map((item,itemIndex)=><Link href={`/prototype/style-10/article/${item.slug}`} key={item.slug}><span>{String(itemIndex+1).padStart(2,"0")}</span><b>{titleInlineText(item)}</b><small>{item.duration||item.type}</small></Link>)}</div></article>;})}</section>; }
function RecommendationRail({ titles }: { titles:Title[] }) { if(!titles.length)return null;return <section className="s10-recommended"><BigLabel label="recommended" /><div>{titles.map((title,index)=><VideoCard index={index} key={title.slug} title={title}/>)}</div></section>; }
function Trending({ titles }: { titles:Title[] }) { if(!titles.length)return null;return <section className="s10-trending" id="popular"><BigLabel label="popular" /><div>{titles.map((title,index)=><Link href={`/prototype/style-10/article/${title.slug}`} key={title.slug} data-s10-reveal><strong>{String(index+1).padStart(2,"0")}</strong><div><p>{titleCategories(title)[0]?.label}</p><h3>{titleInlineText(title)}</h3></div><VideoImage title={title}/><span>{title.duration||title.type}</span><b>▶</b></Link>)}</div></section>; }
function Discover({ categories }: { categories:CategoryTile[] }) { if(!categories.length)return null;return <section className="s10-discover" id="discover"><BigLabel label="discover" /><div>{categories.slice(0,8).map((category,index)=><Link href={`/prototype/style-10/category/${encodeURIComponent(category.slug)}`} key={category.id} data-s10-reveal><CategoryVisual category={category}/><span>0{index+1}</span><h3>{category.name}</h3><b>Browse playlist →</b></Link>)}</div></section>; }
function LatestList({ titles }: { titles:Title[] }) { if(!titles.length)return null;return <section className="s10-latest"><BigLabel label="latest" /><div>{titles.map((title,index)=><Link href={`/prototype/style-10/article/${title.slug}`} key={title.slug} data-s10-reveal><span>{String(index+1).padStart(2,"0")}</span><h3>{titleInlineText(title)}</h3><p>{titleCategories(title)[0]?.label}</p><small>{title.duration||title.type}</small><b>→</b></Link>)}</div></section>; }
function VideoCard({ index,title }: { index:number;title:Title }) { return <Link className={`s10-card s10-card--${index%5}`} href={`/prototype/style-10/article/${title.slug}`} data-s10-reveal><div className="s10-card__visual"><VideoImage portrait={index%5===3} title={title}/><PlayMark label="Play" /></div><div><p>{titleCategories(title)[0]?.label} · {title.duration||title.type}</p><h3>{titleInlineText(title)}</h3><b>Watch →</b></div></Link>; }
function BigLabel({label}:{label:string}){return <header className="s10-big-label" data-s10-reveal><h2>{label}</h2><span>Thai PBS / video stories</span></header>;}
function PlayMark({label}:{label:string}){return <span className="s10-play"><i>▶</i><b>{label}</b></span>;}
function CategoryVisual({category}:{category:CategoryTile}){return <div className="s10-category-visual">{category.imageUrl?<Image alt="" fill sizes="(max-width:700px) 78vw,28vw" src={category.imageUrl}/>:<span data-tone={category.id%4}/>}<i>▶</i></div>;}
function VideoImage({portrait=false,priority=false,title}:{portrait?:boolean;priority?:boolean;title:Title}){const image=portrait?(title.posterImage||title.heroImage):(title.heroImage||title.posterImage);return <div className={`s10-image ${portrait?"s10-image--portrait":""}`}>{image?<Image alt="" fill priority={priority} sizes={portrait?"(max-width:700px) 80vw,30vw":"(max-width:700px) 100vw,65vw"} src={image}/>:<span className="s10-image__fallback" data-tone={Math.abs(hash(title.slug))%4}/>}</div>;}
function StyleTenFooter({categories}:{categories:PrototypeCategory[]}){return <footer className="s10-footer"><div><Link className="s10-brand" href="/prototype/style-10"><b>THAIPBS</b><span>/PLAY</span></Link><p>Stay close to stories worth watching.</p></div><nav>{categories.slice(0,6).map(item=><Link href={`/prototype/style-10/category/${item.slug}`} key={item.slug}>{item.label}</Link>)}</nav><div><span>More stories. More perspectives.</span><a href="#top">Back to top ↑</a></div></footer>;}
function unique(items:Title[]){return [...new Map(items.map(item=>[item.slug,item])).values()];} function hash(value:string){return [...value].reduce((total,character)=>((total<<5)-total)+character.charCodeAt(0),0);} function playlistSections(collections:TitleCollections){const rows:Array<{id:string;title:string;titles:Title[]}>=[];const add=(id:string,title:string,titles:Title[])=>{if(titles.length)rows.push({id,title,titles});};add("recommended","Recommended for you",collections.recommended);for(const row of collections.typeRows)add(`type-${row.type.id}`,row.type.name,row.titles);add("thai","Stories from Thailand",collections.thaiPrograms);add("international","Across the world",collections.internationalPrograms);for(const row of collections.yearRows)add(`year-${row.year}`,`Highlights ${row.year}`,row.titles);return rows;}
